<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Administracin</name>
   <tag></tag>
   <elementGuidId>6b5937bf-d548-4503-a767-a1027ec91391</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.MuiTypography-root.MuiListItemText-primary.MuiTypography-body1.MuiTypography-displayBlock</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/article/div/div/ul/div/div[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>392ff081-bc79-456d-8b2d-b2773a143ab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiListItemText-primary MuiTypography-body1 MuiTypography-displayBlock</value>
      <webElementGuid>5d8e8a4e-dac0-4dd9-b528-c3381a6669bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Administración</value>
      <webElementGuid>d5157e9f-a124-45f3-8275-c70269648985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/article[@class=&quot;makeStyles-root-219&quot;]/div[@class=&quot;MuiDrawer-root MuiDrawer-docked makeStyles-drawer-221 makeStyles-drawerOpen-222&quot;]/div[@class=&quot;MuiPaper-root MuiDrawer-paper makeStyles-drawerOpen-222 MuiDrawer-paperAnchorLeft MuiDrawer-paperAnchorDockedLeft MuiPaper-elevation0&quot;]/ul[@class=&quot;MuiList-root makeStyles-drawerListButton-228 MuiList-padding&quot;]/div[@class=&quot;MuiButtonBase-root MuiListItem-root makeStyles-drawerListItem-226 MuiListItem-gutters MuiListItem-button&quot;]/div[@class=&quot;MuiListItemText-root Component-root-364 makeStyles-drawerItem-225&quot;]/span[@class=&quot;MuiTypography-root MuiListItemText-primary MuiTypography-body1 MuiTypography-displayBlock&quot;]</value>
      <webElementGuid>e5b81652-1e22-407a-a023-e41cd705bed5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/article/div/div/ul/div/div[2]/span</value>
      <webElementGuid>0f4613d5-f882-409b-adec-63bab1bfb618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Control'])[1]/following::span[5]</value>
      <webElementGuid>1e3e1e71-2011-4c3a-b688-086d7e15426d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Servicios'])[1]/following::span[7]</value>
      <webElementGuid>148db82d-f225-4b10-8ec6-0273c379a924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inicio'])[1]/preceding::span[4]</value>
      <webElementGuid>1667c30e-4f95-4f2f-9396-6c4943c0fa31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Protocolos'])[1]/preceding::span[4]</value>
      <webElementGuid>775dd47f-fba0-4cac-8500-55de00879461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Administración']/parent::*</value>
      <webElementGuid>00f5e52a-27d6-402b-be42-6a2ba4c9438a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span</value>
      <webElementGuid>b96fae83-f203-4b76-b215-1253d7a870c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Administración' or . = 'Administración')]</value>
      <webElementGuid>8bacb2e0-44b1-4631-8af4-f2392ff0f308</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
